grails-app/domain/com/mbds/itu/g1/Annonce.groovy
package com.mbds.itu.g1

class Annonce {
    String title
    String description
    Double price

    Date dateCreated
    Date lastUpdated

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static mapping = {
        description type: 'text'
    }

    static constraints = {
        title       nullable: false, blank: false
        description nullable: false, blank: false
        price       min: 0D
    }
}

grails-app/controllers/com/mbds/itu/g1/AnnonceController.groovy
package com.mbds.itu.g1

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import org.springframework.web.servlet.ModelAndView

import static org.springframework.http.HttpStatus.*

class AnnonceController {
    AnnonceService annonceService

    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def versModifier(){
        def idAnnonce = params.idAnnonce
        def annonce = annonceService.get(idAnnonce)
        return new ModelAndView("/annonce/versModifier", [actionPage: "Modifier", pathIllustration: grailsApplication.config.annonces.illustrations.url, annonce: annonce])
    }

    @Secured(['ROLE_ADMIN'])
    def versAjouter(){
        return new ModelAndView("/annonce/versModifier", [actionPage: "Ajouter", pathIllustration: grailsApplication.config.annonces.illustrations.url])
    }

    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond annonceService.list(params), model:[annonceCount: annonceService.count()]
    }
    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def show(Long id) {
        respond annonceService.get(id)
    }
    @Secured('ROLE_ADMIN')
    def create() {
        respond new Annonce(params)
    }
    @Secured('ROLE_ADMIN')
    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }
    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def edit(Long id) {

        respond annonceService.get(id), model: [userList: User.list()/*,pathIllustration: grailsApplication.config.annonces.illustrations.url*/]
    }

    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def update() {
        def annonce = Annonce.get(params.id)
        annonce.title = params.title
        annonce.description = params.description
        annonce.price = Double.parseDouble(params.price)
//        annonce.author = User.get(params.author.id)
        if (annonce == null) {
            notFound()
            return
        }
        /**
         * 1. Récupérer le fichier dans la requête
         * 2. Sauvegarder le fichier localement
         * 3. Créer un illustration sur le fichier que vous avez sauvegardé
         * 4. Attacher l'illustration nouvellement créée à l'annonce
         */

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }
    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/mbds/itu/g1/UserController.groovy
package com.mbds.itu.g1

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class UserController {
    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }
    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def show(Long id) {
        respond userService.get(id)
    }
    @Secured('ROLE_ADMIN')
    def create() {
        respond new User(params)
    }
    @Secured('ROLE_ADMIN')
    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }
    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def edit(Long id) {
        respond userService.get(id)
    }
    @Secured(['ROLE_ADMIN','ROLE_MODERATEUR'])
    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }
    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<a href="#create-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>

    </ul>
</div>
<div id="create-annonce" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.annonce}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form controller="annonce" action="save" method="POST">
        <fieldset class="form">
            <f:all bean="annonce"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <sec:ifAnyGranted roles='ROLE_ADMIN'>
            <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
        </sec:ifAnyGranted>
    </ul>
</div>

<div id="edit-annonce" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.annonce}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:uploadForm controller="annonce" action="update" id="${annonce.id}">
        <g:hiddenField name="version" value="${this.annonce?.version}"/>
        <fieldset class="form">
            <div class="fieldcontain required">
                <label for="title">Title
                    <span class="required-indicator">*</span>
                </label>
                <input type="text" name="title" value="${annonce.title}" required="" id="title">
            </div>

            <div class="fieldcontain required">
                <label for="description">Description
                    <span class="required-indicator">*</span>
                </label>
                <input type="text" name="description" value="${annonce.description}" required=""
                       id="description">
            </div>

            <div class="fieldcontain required">
                <label for="price">Price
                    <span class="required-indicator">*</span>
                </label><input type="number decimal" name="price" value="${annonce.price}" required="" min="0.0" id="price">
            </div>

            <div class="fieldcontain">
                <label for="illustrations">Illustrations</label>
                <g:each in="${annonce.illustrations}" var="illustration">

                    <img src = "${pathIllustration}grails.svg"  width="175"/>
                </g:each>
            </div>

            <div class="fieldcontain">
                <label for="file">Upload</label>
                <input style="display: inline" type="file" name="file" id="file"/>
            </div>

            <div class="fieldcontain required">
                <label for="author">Author
                    <span class="required-indicator">*</span>
                </label>
                <g:select name="author.id" from="${userList}" optionKey="id" optionValue="username" />
            </div>
        </fieldset>
        <fieldset class="buttons">
            <input class="save" type="submit"
                   value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:uploadForm>
</div>
</body>
</html>

grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
<head>


    <meta name="layout" content="main" />

    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

<a href="#list-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/> </a></li>
        <sec:ifAnyGranted roles='ROLE_ADMIN'>
            <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
        </sec:ifAnyGranted>
    </ul>
</div>
<sec:ifAnyGranted roles='ROLE_ADMIN,ROLE_MODERATEUR'>
    <div id="list-annonce" class="content scaffold-list" role="main">
        <h1><g:message code="default.list.label" args="[entityName]" /></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <f:table collection="${annonceList}" />

        <div class="pagination">
            <g:paginate total="${annonceCount ?: 0}" />
        </div>
    </div>
</sec:ifAnyGranted>
</body>
</html>

grails-app/views/annonce/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<a href="#show-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
    </ul>
</div>

<div id="show-annonce" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <f:display bean="annonce" />
    <g:form resource="${this.annonce}" method="DELETE">
        <fieldset class="buttons">
            <sec:ifAnyGranted roles='ROLE_ADMIN,ROLE_MODERATEUR'>
                <g:link class="edit" action="edit" resource="${this.annonce}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
            </sec:ifAnyGranted>
            <sec:ifAnyGranted roles='ROLE_ADMIN'>
                <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </sec:ifAnyGranted>
        </fieldset>
    </g:form>
</div>

</body>
</html>

grails-app/views/annonce/versModifier.gsp
<%--
  Created by IntelliJ IDEA.
  User: rna
  Date: 2021-03-05
  Time: 20:57
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="baseLayout" />
    <title>Lecoincoin_Modifier une annonce</title>
    <style type="text/css">
        .btnMilieu{
            margin-top: 15px;
            text-align: center;
        }
    </style>
</head>

<body>
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">${actionPage} une annonce</h1>
        </div>
            <div class="row">
                    <div class="col-md-12">
                        <!-- Basic Card Example -->
                        <div class="card shadow mb-12">
                            <div class="card-body">
                                <g:form controller="annonce" action="${actionPage}" method="POST">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div>
                                                <label class="text-xs font-weight-bold text-primary text-uppercase">Titre</label><br/>
                                                <g:if test="${actionPage == 'Ajouter'}">
                                                    <input class="form-control" type="text" name="titre" required="true"/>
                                                </g:if>
                                                <g:else>
                                                    <input class="form-control" type="text" name="titre" required="true" value="${annonce.title}"/>
                                                </g:else>
                                            </div>
                                            <div>
                                                <label class="text-xs font-weight-bold text-primary text-uppercase">Prix ($)</label><br/>
                                                <g:if test="${actionPage == 'Ajouter'}">
                                                    <input class="form-control" type="number" name="prix" required="true"/>
                                                </g:if>
                                                <g:else>
                                                    <input class="form-control" type="number" name="prix" required="true" value="${annonce.price}"/>
                                                </g:else>
                                            </div>
                                            <div>
                                                <label class="text-xs font-weight-bold text-primary text-uppercase">Description</label><br/>
                                                <g:if test="${actionPage == 'Ajouter'}">
                                                    <textarea class="form-control" name="description" rows="4" required="true"></textarea>
                                                </g:if>
                                                <g:else>
                                                    <textarea class="form-control" name="description" rows="4" required="true">${annonce.description}</textarea>
                                                </g:else>
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <label class="text-xs font-weight-bold text-primary text-uppercase">Illustrations</label><br/>
                                            <img src = "${pathIllustration}grails.svg"  width="175"/>
                                        </div>
                                    </div>
                                    <div class="btnMilieu">
                                        <g:link controller="menu" action="annonce" class="btn btn-secondary btn-icon-split">
                                            <span class="icon text-gray-600">
                                                <i class="fas fa-arrow-left"></i>
                                            </span>
                                            <span class="text">Annuler</span>
                                        </g:link>
                                        <button class="btn btn-primary btn-icon-split">
                                            <span class="icon text-gray-600">
                                                <i class="fas fa-check"></i>
                                            </span>
                                            <span class="text">Valider</span>
                                        </button>
                                    </div>
                                </g:form>
                            </div>
                        </div>
                    </div>

            </div>

        </div>
        <!-- /.container-fluid -->
    </div>
</body>
</html>